{"name": "test_update_user_with_authorization", "status": "failed", "statusDetails": {"message": "AssertionError: assert 403 == 200\n +  where 403 = <Response [403]>.status_code", "trace": "access_token = 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MWE5ZTQyOWVkMjgwMDAxYjRmMWUxYSIsImlhdCI6MTcyOTc5OTIzNiwiZXhwIjoxNzI5ODAwNDM2fQ.Hv9bm1tcX5hQTHA0_DatgwAVdFs69dKn4r4Wriyix3I'\nuser_data = {'email': 'newemail@yandex.ru', 'name': 'NewUserName'}\n\n    def test_update_user_with_authorization(access_token, user_data):\n        \"\"\"Тест обновления данных пользователя с авторизацией\"\"\"\n        headers_with_auth = {\n            \"Content-Type\": \"application/json\",\n            \"Authorization\": access_token  # Добавляем access token\n        }\n        response = requests.patch(BASE_URL, json=user_data, headers=headers_with_auth)\n    \n        # Проверяем успешность запроса\n>       assert response.status_code == 200\nE       assert 403 == 200\nE        +  where 403 = <Response [403]>.status_code\n\ntests/test_change_data_user.py:48: AssertionError"}, "description": "Тест обновления данных пользователя с авторизацией", "start": 1729799236475, "stop": 1729799237395, "uuid": "51307ee1-a281-4cee-85b8-15aa52c4414a", "historyId": "1d864b93728c899d28e5ff0168fc16f0", "testCaseId": "1d864b93728c899d28e5ff0168fc16f0", "fullName": "tests.test_change_data_user#test_update_user_with_authorization", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_change_data_user"}, {"name": "host", "value": "falcon.local"}, {"name": "thread", "value": "44820-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_change_data_user"}]}